apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demoweb
spec:
  chart:
    git: https://github.com/tkubica12/edge-k3s-arc
    ref: master
    path: helm/demoweb
  values:
    version: "1"
    info: k3s-3