apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myweb-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: myweb-service
              servicePort: 80